# Generated by Django 2.2.5 on 2020-02-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200208_2137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facilitiy',
            new_name='Facility',
        ),
    ]
