# Generated by Django 2.2.5 on 2020-02-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200214_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facility',
            new_name='Facilitiy',
        ),
    ]
